### ISSUE TITLE
Problem with Brew install.

### ISSUE THREAD

**Issue by leebaird** [rofl0r/proxychains-ng#138]
proxychains4 nmap -iL targets.txt -Pn -n -T4 --open -p- --stats-every 10s -oA nmap
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
dyld: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: mach-o, but wrong architecture

Trace/BPT trap: 5

**Comment by rofl0r** [comment]
tell the brew package maintainers to add `--fat-binary` when they call configure.

**Comment by Red54** [comment]
I met a different problem.

$ proxychains4 git clone https://bitbucket.org/superr/superrs-kitchen.git
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.11
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
Cloning into 'superrs-kitchen'...
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
remote: Counting objects: 582, done.
remote: Compressing objects: 100% (500/500), done.
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
Receiving objects:  12% (70/582), 1.72 MiB | 29.00 KiB/s

**Comment by rofl0r** [comment]
sorry - we can not help you here with brew problems. please open an issue on the homebrew issue tracker, thanks.
