### ISSUE TITLE
Including whitelisted headers with an upstream CONNECT request

### ISSUE THREAD

**Issue by corford** [rofl0r/proxychains-ng#158]
For similar reasons to https://github.com/request/request/issues/1019 it would be great if there was a way to specify a whitelist of headers which, if present in the original wrapped application request, should be included with the CONNECT request to upstream proxies.

Real world example: passing a custom header from the proxychained app to an upstream squid proxy which could then be processed with an external acl helper (e.g. to allow/deny the request)

**Comment by rofl0r** [comment]
proxychains is not about http, it is creating generic connections over different types of proxies using one *or more* proxies.
your use case is only for scenario http connection over http proxy.
also, since it requires injecting these pseudo-auth headers, proxified app is probably custom program or script, so it should be easy to equip it with http proxy function directly.
using headers for such a type of authentication looks like cheap hack though.
as for implementation of this feature:
currently proxychains creates chain of proxy connections when libc calls connect().
this is prior to any data sent from the client, so proxychains cannot know which headers will be in subsequent http request. implementing it would require postponing the connect after first send was executed, which means if connection fails we cannot return proper error code at the right spot. additionally parsing first packet for HTTP stuff can introduce vulns.
so in light of all this it seems like a bad idea implementing all this just for one really exotic and hackish use case.

**Comment by corford** [comment]
Thanks for the detailed reply. Agree such a feature is not worth the code complexity given the changes that would be necessary to implement it.

As for the "why". In our case we were interested in it as a "hackish" workaround for some limitations with how squid sends requests to upstream cache_peers after SSL interception. By wrapping squid with proxychains we solve the upstream problem but lose the ability to further process the request once it hits our upstream cache_peer (since at that point all the upstream sees is a binary CONNECT tunnel). Some extra headers with that CONNECT request would have given us a few more hooks to play with :)

**Comment by corford** [comment]
Sorry @rofl0r I've just re-read your reply and am wondering if we are talking about the same thing? When I talk about CONNECT I am referring to the HTTP proxy tunnelling method for encapsulating https traffic not the libc connect() call.

**Comment by rofl0r** [comment]
yes. during connect(), HTTP CONNECT is sent to target proxy. this happens before hooked process sends data, which will contain HTTP request for destination host.
since we agree that implementing it is not feasible i go ahead and close this.
