### ISSUE TITLE
SSL proxy is it supported 

### ISSUE THREAD

**Issue by instagramlover** [rofl0r/proxychains-ng#186]
Well in socat i use to use this type : 
socat TCP-LISTEN:9180,fork SSL:204.52.135.200:443,verify=0

Dos proxychains-ng support https/SSL proxy

**Comment by rofl0r** [comment]
https proxies are currently not supported, and i believe adding support for it would not be straightforward (for example using openssl,etc you can SSL-wrap a socket, but if there's more than one SSL-proxy in the chain, how would you wrap the socket again ? i doubt that it can be done easily). additionally, pulling in dependencies to another library can break all sorts of things considering we're hooking libc. so i dont see this being implemented anytime soon. maybe kneesocks would be a more appropriate tool to add support for this, since it has to deal with a single proxy only.
