### ISSUE TITLE
Allow specifying dns names as proxy hosts

### ISSUE THREAD

**Issue by crass** [rofl0r/proxychains-ng#25]
I realize this was disabled in a previous issue.  However, there are plenty of cases where dns names can be allowed.  For instance, when proxy_dns is off.  Perhaps there should be a new option proxy_proxy_dns which should take a parameter, one of: force, disallow, if_possible.

* force - ensures that no dns requests are leaked.
* disallow - all dns is done locally
* if_possible - resolve remotely if possible, otherwise do it locally.

Note that if proxy_proxy_dns = force could still allow proxies to be specified as DNS names by proxying the dns through the partially created proxy chain.

**Comment by muelli** [comment]
It's easy to resolve the name to an IP address. But that address might change. But the name, e.g. `proxy.acme.corp` will very likely stay the same.

Also, I'm trying to use proxychains behind a corporate proxy which requires authentication, because some software I want to provision does not deal well with such proxies. Hence, I am trying to install proxychains. And I'm using ansible for provisioning.  Ansible, however, does not resolve hostnames and it seems much easier to make proxychains accept a hostname instead of making Ansible do something totally unrelated to its purpose.

**Comment by ajthemacboy** [comment]
I'd really like this ability as well. Say I want to use a proxy, say the PIA proxy `proxy-nl.privateinternetaccess.com`, but I don't want to manually specify each IP from `nslookup`.

**Comment by rofl0r** [comment]
yeah, you don't want to manually specify ips and i don't want to code the feature you want.
