### ISSUE TITLE
[Feature request] Record packets in pcap format

### ISSUE THREAD

**Issue by aliyuchang33** [rofl0r/proxychains-ng#306]
Searched for the whole net to capture packets by process. No one works. The proxychains should be easy to implement a packet capture functionality to do so. Would this be implemented in the future?

**Comment by rofl0r** [comment]
a good idea basically. however you'd never get a direct relation between packets and data received/sent (assuming we'd hook those, which we don't) since the process which has proxychains injected receives data from a kernel buffer and can't really know where a packet started and ended. the kernel may merge several packets into a single buffer, or even deliver only partial packets.
if that's a non-issue, then i guess something like this could be done, but with something that hooks not only connection setup, but also the data transfers using read/write/recv/send etc.
but i think this is out of scope for proxychains-ng itself.
