### ISSUE TITLE
Hi, Could we use Proxychains-ng  for an App on Android or iOS ?

### ISSUE THREAD

**Issue by fuqiangleon** [rofl0r/proxychains-ng#378]
We want to find a method to redirect traffic of an App to a socks5 proxy. we think maybe Proxychains-ng is a good solution, but we don't know that does it support Android or iOS ?

Hope to get your help, thx.

**Comment by rofl0r** [comment]
proxychains-ng works on OSX, linux, freebsd. since android development requires a multi-gigabyte java SDK, and iOs development an apple-registered (and paid) developer account, i can't help with those, but i've seen someone doing a port (do a github search) so it's both technically possible. for android probably the best solution is a termux environment.

**Comment by rofl0r** [comment]
proxychains-ng works on OSX, linux, freebsd. since android development requires a multi-gigabyte java SDK, and iOs development an apple-registered (and paid) developer account, i can't help with those, but i've seen someone doing a port (do a github search) so it's both technically possible. for android probably the best solution is a termux environment.
