### ISSUE TITLE
proxy not working with none command line programs?

### ISSUE THREAD

**Issue by calidion** [rofl0r/proxychains-ng#487]
config file:

```
dynamic_chain
proxy_dns 
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5	127.0.0.1	1080
```
use 

> proxychains curl

works well.

use

>proxychains firefox

cann't work.

**Comment by rofl0r** [comment]
1) read the sample config file, it suggests to use proxy_dns_daemon with browsers
2) don't use "snap" or other containerized version of browser, but one from apt repos.

**Comment by calidion** [comment]
proxychains obs-studio doesn't work either.

**Comment by rofl0r** [comment]
whatever program it is, proxychains doesn't work with containerized versions, because the very purpose of containers is to shield them from the guest operating systems. unfortunately it recently became a trend (thanks to use of languages like rust and go with micro-dependencies) to ship apps in such containers. snap and flatpack among others are such formats, so you need to get a native version of your app instead.

**Comment by calidion** [comment]
@rofl0r 

Thanks.  It works now after removing the snap version and reinstalled a deb version.
