### ISSUE TITLE
CVE-2015-3887 - RPATH flaw

### ISSUE THREAD

**Issue by pranavk** [rofl0r/proxychains-ng#60]
https://github.com/rofl0r/proxychains-ng/blob/master/src/main.c#L35
This line loads libproxychains4.so from the current directory which can be used by the attacker to load a manipulated library instead of original libproxychains4.so

ref:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3887
http://seclists.org/oss-sec/2015/q2/415
http://seclists.org/oss-sec/2015/q2/430

**Comment by rofl0r** [comment]
Thanks for the information. It is a feature of proxychains-ng to allow the user to preload  the DSO from the current directory. I understand though that with more and more mainstream distros adopting proxychains-ng it is probably better to ship with more "defensive" default settings. I'm currently thinking about the best way to achieve that, probably with a compile-time switch.

**Comment by mtasaka** [comment]
Well, I already told Pranav that when building proxychains-ng (before installing), libproxychains4.so and proxychains are created on the same directory, and when trying to use proxychains4 on the build directory (as ./proxychains4), libproxychains4 on the same directory is loaded, because of own_dir entry, so there should be no problem when trying to use proxychains4 on the build directory (without installing). 

On the contrary, allowing arbitrary "." is security flaw. In this sense, 
https://github.com/rofl0r/proxychains-ng/blob/master/src/main.c#L51
is also dangerous. If l is 0, some system-wide directory (like "/lib") shoule be returned.

Or you can use realpath(argv0, NULL)
http://man7.org/linux/man-pages/man3/realpath.3.html

**Comment by mtasaka** [comment]
Note that realpath() resolves symlink, so using realpath() avoilds symlink attack.
