### ISSUE TITLE
Cannot work with IPv6/Maven on MacOSX

### ISSUE THREAD

**Issue by linkerlin** [rofl0r/proxychains-ng#77]
pc4 mvn install
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-http-shared/2.9/wagon-http-shared-2.9.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-http/2.9/wagon-http-2.9.jar
[proxychains] Strict chain  ...  127.0.0.1:1080 [proxychains] Strict chain  ...  127.0.0.1:1080 [proxychains] Strict chain  ...  127.0.0.1:1080 [proxychains] Strict chain  ...  127.0.0.1:1080  ...  ::ffff:[inet_ntoa error]:443  ...  ::ffff:224.0.0.1:443  ...  ::ffff:224.0.0.1:443  ...  ::ffff:224.0.0.1:443 <--socket error or timeout!
<--socket error or timeout!
<--socket error or timeout!

**Comment by linkerlin** [comment]
With wget/curl is ok.

**Comment by rofl0r** [comment]
interesting that you have several "DLL init: proxychains-ng 4.10-git-10-g2237749" lines printed.
is that also the case with wget/curl ?
it seems the error you're getting is because maven is translating the ipv4 address proxychains hands out (224.0.0.1) to an ipv6 address (::ffff:224.0.0.1:443) and proxychains fails to detect that its one of its internal addresses (which are used for remote DNS mappings)
